spring.application.name=interview-coach

# Open AI設定
spring.ai.openai.api-key=${GITHUB_KEY}
spring.ai.openai.base-url=https://models.inference.ai.azure.com
spring.ai.openai.chat.options.model=gpt-4.1-nano
spring.ai.openai.chat.completions-path=/chat/completions

# 伺服器port
server.port=8080